<?php

namespace UCI\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EstudianteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstudianteRepository extends EntityRepository
{
}
